### ISSUE TITLE
Allow for defining bashd_entry with inline content

### ISSUE THREAD

**Issue by tknerr** [jakshi/bashd#3]
I have a few `bashd_entry`s which are so tiny I don't want to create an additional file in `templates/default/*.sh.erb` each.

The [bash cookbook](https://github.com/optiflows-cookbooks/bash#syntax) allows you to inline the contents of the shell scripts via the `content` parameter. For bashd it could look like this:

```ruby
bashd_entry "set-up-my-env" do
  user "me"
  content "export FOO=bar"
end
```

I think both options (separate file and inline script) are useful. 

What do you think?

**Comment by tknerr** [comment]
The relevant implementation part is this I guess:
https://github.com/optiflows-cookbooks/bash/blob/master/providers/profile.rb#L8-16

**Comment by jakshi** [comment]
I could:

* add content to resource, with default nil
* add condition in provider, to use content attribute if it's not nil and template if it's nil.

**Comment by tknerr** [comment]
@jakshi sweeeeeet, thanks! :-) :+1:

**Comment by jakshi** [comment]
You're welcome.
I'm glad that you like it.
Actually it (coding) becomes really interesting only when somebody using your code.

**Comment by tknerr** [comment]
Fully agree. I'm using it and probably many others too. This cookbook was just missing and I almost started writing it myself, but then I was glad to find you already did :-)
